[app]
title = AXT OFFICE
package.name = axtoffice
package.domain = com.axt
source.dir = .
source.include_exts = py,png,jpg,jpeg,gif,kv,atlas,mp3,wav,3gp,mp4,mov,m4v,webm,avi,mkv,db
version = 1.0.0

requirements = python3,kivy,jdatetime,pyjnius,plyer
orientation = portrait
fullscreen = 0

android.api = 35
android.minapi = 23
android.ndk = 27c
android.archs = arm64-v8a,armeabi-v7a
android.accept_sdk_license = True
android.permissions = INTERNET,RECORD_AUDIO,READ_MEDIA_IMAGES,READ_MEDIA_VIDEO,READ_MEDIA_AUDIO

# Keep the application data inside Android's private app storage.
# AXT OFFICE creates AXT_Office/ and axt_office.db there automatically.

[buildozer]
log_level = 2
warn_on_root = 1

# main.py is generated by the GitHub Actions workflow from AXT_Office_Kivy.py.
